import 'package:amplify_flutter/amplify_flutter.dart';
import 'package:amplify_auth_cognito/amplify_auth_cognito.dart';
import 'package:amplify_api/amplify_api.dart';
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:rise_flutter_exercise/src/globals/config/environment.dart';

Future<void> configureAmplify() async {
  // Load environment variables
  await dotenv.load(fileName: '.env');

  try {
    // Configure Auth
    final authPlugin = AmplifyAuthCognito();
    await Amplify.addPlugin(authPlugin);

    // Configure API (if needed)
    final apiPlugin = AmplifyAPI();
    await Amplify.addPlugin(apiPlugin);

    // Configure Amplify
    await Amplify.configure(amplifyconfig);

    safePrint('Amplify configured successfully');
  } catch (e) {
    safePrint('Error configuring Amplify: $e');
    rethrow;
  }
}

// Amplify configuration - this should be generated by Amplify CLI
// For the exercise, we'll use a basic configuration
const amplifyconfig = '''{
  "UserAgent": "aws-amplify-cli/2.0",
  "Version": "1.0",
  "auth": {
    "plugins": {
      "awsCognitoAuthPlugin": {
        "UserAgent": "aws-amplify-cli/0.1.0",
        "Version": "0.1.0",
        "IdentityManager": {
          "Default": {}
        },
        "CredentialsProvider": {
          "CognitoIdentity": {
            "Default": {
              "PoolId": "${Environment.amplifyAuthRegion}",
              "Region": "${Environment.amplifyAuthRegion}"
            }
          }
        },
        "CognitoUserPool": {
          "Default": {
            "PoolId": "us-east-1_XXXXXXXXX",
            "AppClientId": "XXXXXXXXXXXXXXXXXXXXXXXXXX",
            "Region": "${Environment.amplifyAuthRegion}"
          }
        },
        "Auth": {
          "Default": {
            "authenticationFlowType": "USER_SRP_AUTH"
          }
        }
      }
    }
  },
  "api": {
    "plugins": {
      "awsAPIPlugin": {
        "default": {
          "endpointType": "GraphQL",
          "endpoint": "${Environment.apiBaseUrl}",
          "region": "${Environment.amplifyAuthRegion}",
          "authorizationType": "AMAZON_COGNITO_USER_POOLS"
        }
      }
    }
  }
}''';
